Repository CSClubIIITDM/hacktoberfest-advanced, pull requests merged in 2022-10, with the labels that each got.

#1 Update HailDoofania.md
  cp/Questions/HailDoofania.md
Labels: documentation, hacktoberfest-accepted

#3 Corrected inconsistencies in MinimumPathSum(CP)
  cp/Questions/MinimumPathSum.md
Labels: documentation

#22 solved air conditioner using c
  cp/c/AirConditioner.c
Labels: hacktoberfest-accepted

#24 solved MinimumPathSum problem in python
  cp/Questions/MinimumPathSum.md
  cp/Questions/Minimumsumpath.png
  cp/python/MinimumPathSum.py
Labels: hacktoberfest-accepted

#26 made a basic solution template for cs club website
  webdev/jashwanth_cs20b1007/app.js
  webdev/jashwanth_cs20b1007/img/hero-bg.png
  webdev/jashwanth_cs20b1007/img/img-1.png
  webdev/jashwanth_cs20b1007/img/img-2.png
  webdev/jashwanth_cs20b1007/index.html
  webdev/jashwanth_cs20b1007/style.css
Labels: hacktoberfest-accepted

#27 created a Readme for website solution
  webdev/jashwanth_cs20b1007/README.md
  webdev/jashwanth_cs20b1007/Screenshot 2022-10-31 233559.png
  webdev/jashwanth_cs20b1007/Screenshot 2022-10-31 233618.png
  webdev/jashwanth_cs20b1007/Screenshot 2022-10-31 233641.png
  webdev/jashwanth_cs20b1007/main_page.png
Labels: hacktoberfest-accepted
